# Generated by Django 5.1.15 on 2026-07-03 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0004_order_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="montant (FCFA)"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("manuel", "Saisie manuelle"),
                        ],
                        db_index=True,
                        default="mobile_money",
                        max_length=16,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                        ],
                        db_index=True,
                        default="en_attente",
                        max_length=12,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone payeur"
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="réseau MoMo"
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(
                        blank=True,
                        help_text="Clé du provider (ex. 'tara'). Vide pour une saisie manuelle.",
                        max_length=24,
                    ),
                ),
                (
                    "reference_externe",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identifiant de transaction du provider (paymentId Tara).",
                        max_length=64,
                    ),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Envoyée à Tara comme productId — empêche le double encaissement.",
                        unique=True,
                    ),
                ),
                ("gateway_initiated_at", models.DateTimeField(blank=True, null=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("motif_rejet", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="commande",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "verbose_name_plural": "paiements",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["statut", "source"],
                        name="payments_pa_statut_7673e0_idx",
                    ),
                    models.Index(
                        fields=["order", "-created_at"],
                        name="payments_pa_order_i_288dd3_idx",
                    ),
                ],
            },
        ),
    ]
