# Generated by Django 5.1.15 on 2026-06-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_order_delivery_fee_alter_order_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "phone",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="téléphone"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="disponible"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "livreur",
                "verbose_name_plural": "livreurs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="zone / quartier"),
                ),
                (
                    "city",
                    models.CharField(
                        default="Douala", max_length=80, verbose_name="ville"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="frais de livraison (FCFA)",
                    ),
                ),
                (
                    "eta_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Temps de livraison estimé en minutes.",
                        verbose_name="délai estimé (min)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
            ],
            options={
                "verbose_name": "zone de livraison",
                "verbose_name_plural": "zones de livraison",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "À assigner"),
                            ("assigned", "Assignée (attente livreur)"),
                            ("accepted", "Acceptée par le livreur"),
                            ("completed", "Livrée & validée"),
                            ("expired", "Expirée (non acceptée)"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="statut",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="assignée le"
                    ),
                ),
                (
                    "acceptance_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="échéance d'acceptation"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="acceptée le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="livrée le"
                    ),
                ),
                (
                    "delivery_code",
                    models.CharField(
                        blank=True,
                        help_text="Code unique communiqué au client, saisi par le livreur.",
                        max_length=10,
                        verbose_name="code de livraison",
                    ),
                ),
                (
                    "flagged_for_review",
                    models.BooleanField(
                        default=False,
                        help_text="Remontée au numéro service du soir pour vérification.",
                        verbose_name="à vérifier (service)",
                    ),
                ),
                (
                    "reviewed",
                    models.BooleanField(default=False, verbose_name="vérifiée"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="delivery.courier",
                        verbose_name="livreur",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="orders.order",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="delivery.deliveryzone",
                        verbose_name="zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "livraison",
                "verbose_name_plural": "livraisons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="courier",
            name="zones",
            field=models.ManyToManyField(
                blank=True,
                related_name="couriers",
                to="delivery.deliveryzone",
                verbose_name="zones couvertes",
            ),
        ),
    ]
