# Generated by Django 5.1.15 on 2026-06-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="city",
            field=models.CharField(
                default="Douala", max_length=80, verbose_name="ville"
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, verbose_name="code OTP"),
        ),
        migrations.AddField(
            model_name="courier",
            name="otp_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="OTP expire le"
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="vehicle",
            field=models.CharField(
                blank=True,
                default="Moto",
                max_length=40,
                verbose_name="moyen de transport",
            ),
        ),
    ]
