# Generated by Django 5.1.15 on 2026-07-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_remove_courier_otp_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("courier_to_platform", "Livreur → plateforme"),
                            ("platform_to_courier", "Plateforme → livreur"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "is_cod",
                    models.BooleanField(
                        default=True,
                        help_text="True = cash encaissé par le livreur ; False = payé en ligne.",
                        verbose_name="paiement à la livraison",
                    ),
                ),
                (
                    "collected",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="encaissé par le livreur (FCFA)",
                    ),
                ),
                (
                    "courier_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="commission livreur (FCFA)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="montant à régler (FCFA)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "En attente"), ("settled", "Réglé")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="réglé le"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements",
                        to="delivery.courier",
                    ),
                ),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement",
                        to="delivery.delivery",
                    ),
                ),
            ],
            options={
                "verbose_name": "décaissement",
                "verbose_name_plural": "décaissements",
                "ordering": ["-created_at"],
            },
        ),
    ]
