# Generated by Django 5.1.15 on 2026-06-29 16:23

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="nom complet"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optionnel — permet la connexion / l'OTP par téléphone.",
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="téléphone",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("courier", "Livreur"),
                            ("admin", "Admin"),
                        ],
                        default="client",
                        max_length=12,
                        verbose_name="rôle",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Accès au CMS produits et à l'admin Django/Wagtail.",
                        verbose_name="équipe (accès admin)",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="inscrit le"
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(blank=True, max_length=6, verbose_name="code OTP"),
                ),
                (
                    "otp_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="OTP expire le"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
    ]
