"""
Django settings for tchokos project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

from dotenv import load_dotenv

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

# Charge les variables d'environnement depuis .env à la racine du projet
load_dotenv(os.path.join(BASE_DIR, ".env"))


def env(key, default=""):
    return os.environ.get(key, default)


def env_bool(key, default=False):
    return env(key, str(default)).lower() in ("1", "true", "yes", "on")


def env_list(key, default=""):
    return [v.strip() for v in env(key, default).split(",") if v.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    # Apps métier Tchokos
    "accounts",
    "catalog",
    "orders",
    "delivery",
    "payments",
    "vendors",
    "siteconfig",
    "integrations",
    "api",
    "home",
    "search",
    # Wagtail
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.api.v2",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    # API / tiers
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "anymail",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "tchokos.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tchokos.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Africa/Douala"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default storage settings, with the staticfiles storage updated.
# See https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # ManifestStaticFilesStorage is recommended in production, to prevent
    # outdated JavaScript / CSS assets being served from cache
    # (e.g. after a Wagtail upgrade).
    # See https://docs.djangoproject.com/en/5.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}


# Wagtail settings

WAGTAIL_SITE_NAME = "tchokos"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = [
    "csv",
    "docx",
    "key",
    "odt",
    "pdf",
    "pptx",
    "rtf",
    "txt",
    "xlsx",
    "zip",
]

# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 24,
}

# ---------------------------------------------------------------------------
# Authentification — User custom (email) + JWT
# ---------------------------------------------------------------------------
AUTH_USER_MODEL = "accounts.User"

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# ---------------------------------------------------------------------------
# CORS — autorise le frontend Next.js à appeler l'API
# ---------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000"
)
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", "http://localhost:3000")

# ---------------------------------------------------------------------------
# Intégrations
# ---------------------------------------------------------------------------
# Brevo (emails transactionnels) — via django-anymail (backend Brevo standard).
# Les 3 variables suffisent à activer Brevo : BREVO_API_KEY + expéditeur
# (BREVO_SENDER_NAME / BREVO_SENDER_EMAIL, agrégés dans DEFAULT_FROM_EMAIL).
BREVO_API_KEY = env("BREVO_API_KEY")
BREVO_SENDER_NAME = env("BREVO_SENDER_NAME", "Tchokos")
BREVO_SENDER_EMAIL = env("BREVO_SENDER_EMAIL", "no-reply@tchokos-sarl.com")
DEFAULT_FROM_EMAIL = f"{BREVO_SENDER_NAME} <{BREVO_SENDER_EMAIL}>"
EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
ANYMAIL = {"BREVO_API_KEY": BREVO_API_KEY}

# URL du frontend (liens dans les emails : reset de mot de passe, etc.)
FRONTEND_URL = env("FRONTEND_URL", "http://localhost:3000")

# Tara Money (paiement Mobile Money — MTN MoMo / Orange Money Cameroun)
TARA_API_KEY = env("TARA_API_KEY")
TARA_MERCHANT_ID = env("TARA_MERCHANT_ID")
# Tara ne signe pas ses webhooks (pas de HMAC) ; ce secret reste inutilisé,
# la sécurité repose sur HTTPS + URL secrète + vérif du businessId/merchantId.
TARA_WEBHOOK_SECRET = env("TARA_WEBHOOK_SECRET")
# Base publique HTTPS du backend — sert à construire l'URL de webhook envoyée
# à Tara ({PUBLIC_BASE_URL}/api/payments/webhook/tara/). Indispensable en prod.
PUBLIC_BASE_URL = env("PUBLIC_BASE_URL", "http://localhost:8010")
# Modes test — À LAISSER FALSE EN PROD (valident un paiement sans Tara / sans
# contrôle de montant). Réservés à la recette locale.
PAYMENTS_TEST_AUTO_VALIDATE = env_bool("PAYMENTS_TEST_AUTO_VALIDATE", False)
PAYMENTS_TEST_ALLOW_ANY_AMOUNT = env_bool("PAYMENTS_TEST_ALLOW_ANY_AMOUNT", False)

# OpenRouter (chatbot / assistant Tchokos)
OPENROUTER_API_KEY = env("OPENROUTER_API_KEY")
OPENROUTER_MODEL = env("OPENROUTER_MODEL", "openai/gpt-4o-mini")

# Sendo (plateforme de suivi de livraison — branchement externe)
SENDO_API_URL = env("SENDO_API_URL", "")
SENDO_API_KEY = env("SENDO_API_KEY", "")
SENDO_WEBHOOK_SECRET = env("SENDO_WEBHOOK_SECRET", "")
# Base publique Sendo pour les liens de suivi colis ouverts par le client
# (peut différer de l'URL API : ex. tunnel HTTPS pour le mobile). Défaut = API.
SENDO_PUBLIC_URL = env("SENDO_PUBLIC_URL", SENDO_API_URL)

# Livraison : délai (heures) laissé au livreur pour accepter une course
DELIVERY_ACCEPT_WINDOW_HOURS = int(env("DELIVERY_ACCEPT_WINDOW_HOURS", "4"))
# Numéro service de la plateforme (rapport du soir des livraisons non validées)
PLATFORM_SERVICE_PHONE = env("PLATFORM_SERVICE_PHONE", "")

# Personnalisation de l'admin Django (back-office produits dédié)
WAGTAIL_SITE_NAME = "Tchokos"
