# Generated by Django 5.1.15 on 2026-06-28 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nom")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=140, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="image",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ordre d'affichage"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "catégorie",
                "verbose_name_plural": "catégories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nom")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=120, verbose_name="marque"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Prix de vente en francs CFA.",
                        max_digits=12,
                        verbose_name="prix (FCFA)",
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Ancien prix, affiché barré pour signaler une promo. Optionnel.",
                        max_digits=12,
                        null=True,
                        verbose_name="prix barré (FCFA)",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("femme", "Femme"),
                            ("homme", "Homme"),
                            ("enfant", "Enfant"),
                            ("unisexe", "Unisexe"),
                        ],
                        default="unisexe",
                        max_length=10,
                        verbose_name="cible",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Aucun"),
                            ("nouveau", "Nouveau"),
                            ("promo", "Promo"),
                            ("bestseller", "Meilleure vente"),
                            ("made_in_cmr", "Made in Cameroun"),
                        ],
                        default="",
                        max_length=12,
                        verbose_name="badge",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="référence (SKU)"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="stock"),
                ),
                (
                    "sizes",
                    models.CharField(
                        blank=True,
                        help_text="Liste libre séparée par des virgules, ex: 40, 41, 42.",
                        max_length=200,
                        verbose_name="tailles disponibles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="en ligne"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="mis en avant"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "produit",
                "verbose_name_plural": "produits",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="image"),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="texte alternatif"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="image principale"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo produit",
                "verbose_name_plural": "photos produit",
                "ordering": ["-is_primary", "order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="catalog_pro_is_acti_e6e001_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="catalog_pro_categor_891fe8_idx"
            ),
        ),
    ]
