# Generated by Django 5.1.15 on 2026-06-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Utilisée si aucune image n'est téléversée.",
                verbose_name="image (URL externe)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Utilisée si aucune photo n'est téléversée. Pratique pour la démo.",
                verbose_name="image (URL externe)",
            ),
        ),
    ]
