# Generated by Django 5.1.15 on 2026-06-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=120, verbose_name="nom du client"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="note (1-5)"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="commentaire")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="publié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="date"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "avis",
                "verbose_name_plural": "avis",
                "ordering": ["-created_at"],
            },
        ),
    ]
