# Generated by Django 5.1.15 on 2026-06-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Utilisée si aucune image n'est téléversée.",
                verbose_name="image (URL externe)",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="products/", verbose_name="image"
            ),
        ),
    ]
