# Generated by Django 5.1.15 on 2026-06-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="nom du responsable"),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=150, verbose_name="nom de la boutique"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="téléphone"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "vendeur",
                "verbose_name_plural": "vendeurs",
                "ordering": ["shop_name"],
            },
        ),
    ]
