# Generated by Django 5.1.15 on 2026-06-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Tchokos", max_length=100, verbose_name="Nom du site"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Chaussures & vêtements — la marque du Cameroun",
                        max_length=200,
                        verbose_name="Accroche",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Format international sans +, ex: 2376XXXXXXXX",
                        max_length=30,
                        verbose_name="Numéro WhatsApp",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contact"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="Akwa, en face du Faya Hôtel, immeuble Socsuba — Douala",
                        max_length=255,
                        verbose_name="Adresse",
                    ),
                ),
                ("tiktok_url", models.URLField(blank=True, verbose_name="TikTok")),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
            ],
            options={
                "verbose_name": "Marque & contact",
            },
        ),
    ]
