# Generated by Django 5.1.15 on 2026-07-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandsettings",
            name="notify_client_email",
            field=models.BooleanField(
                default=True,
                help_text="Envoi du code de livraison et notifications au client par email (Brevo).",
                verbose_name="Notifier les clients par email",
            ),
        ),
        migrations.AddField(
            model_name="brandsettings",
            name="notify_client_whatsapp",
            field=models.BooleanField(
                default=False,
                help_text="Nécessite un fournisseur d'API WhatsApp Business (à configurer). Sans effet tant que non branché.",
                verbose_name="Notifier les clients par WhatsApp",
            ),
        ),
    ]
