# Generated by Django 5.1.15 on 2026-07-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0002_brandsettings_notify_client_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("internal", "Interne (livreurs Tchokos)"),
                            ("external", "Externe (prestataire)"),
                            ("both", "Les deux (interne + externe)"),
                        ],
                        default="internal",
                        max_length=12,
                        verbose_name="Mode de livraison",
                    ),
                ),
                (
                    "auto_assign",
                    models.BooleanField(
                        default=True,
                        help_text="Assigner automatiquement chaque commande à un livreur. Sinon l'admin assigne à la main.",
                        verbose_name="Assignation automatique",
                    ),
                ),
                (
                    "assign_strategy",
                    models.CharField(
                        choices=[
                            ("first_available", "Premier livreur disponible"),
                            ("nearest", "Livreur le plus proche (distance)"),
                        ],
                        default="first_available",
                        help_text="« Le plus proche » nécessite les coordonnées des zones et des livreurs.",
                        max_length=20,
                        verbose_name="Stratégie d'assignation",
                    ),
                ),
                (
                    "acceptance_window_hours",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Temps laissé au livreur pour accepter avant expiration.",
                        verbose_name="Délai d'acceptation (heures)",
                    ),
                ),
                (
                    "commission_mode",
                    models.CharField(
                        choices=[
                            (
                                "fixed_fee",
                                "Frais de livraison (le livreur garde les frais)",
                            ),
                            ("percentage", "Pourcentage du sous-total"),
                        ],
                        default="fixed_fee",
                        max_length=12,
                        verbose_name="Mode de commission",
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Utilisé si mode = pourcentage. Ex: 10 = 10% du sous-total.",
                        max_digits=5,
                        verbose_name="Commission (%)",
                    ),
                ),
                (
                    "notify_courier",
                    models.BooleanField(
                        default=True,
                        verbose_name="Notifier le livreur d'une nouvelle course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison",
            },
        ),
    ]
