# Generated by Django 5.1.15 on 2026-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0003_deliverysettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandsettings",
            name="whatsapp_arrivages",
            field=models.CharField(
                blank=True,
                help_text="Numéro du canal « nouveaux arrivages ». Format sans +, ex: 2376XXXXXXXX",
                max_length=30,
                verbose_name="WhatsApp groupe arrivages",
            ),
        ),
        migrations.AlterField(
            model_name="brandsettings",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="Format international sans +, ex: 2376XXXXXXXX",
                max_length=30,
                verbose_name="Numéro WhatsApp (commande)",
            ),
        ),
    ]
