# Generated by Django 5.1.15 on 2026-06-28 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="référence"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=150, verbose_name="nom du client"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="téléphone")),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="ville"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="adresse / quartier"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note du client")),
                (
                    "channel",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("tara", "Tara Money")],
                        default="whatsapp",
                        max_length=12,
                        verbose_name="canal",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("contacted", "Client contacté"),
                            ("confirmed", "Confirmée"),
                            ("paid", "Payée"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="statut",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="total (FCFA)",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="référence paiement"
                    ),
                ),
                (
                    "payment_link",
                    models.URLField(blank=True, verbose_name="lien de paiement"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifiée le"),
                ),
            ],
            options={
                "verbose_name": "commande",
                "verbose_name_plural": "commandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="produit"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="prix unitaire"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantité"),
                ),
                (
                    "size",
                    models.CharField(blank=True, max_length=30, verbose_name="taille"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de commande",
                "verbose_name_plural": "lignes de commande",
            },
        ),
    ]
