# Generated by Django 5.1.15 on 2026-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="frais de livraison (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="sous-total articles (FCFA)",
            ),
        ),
    ]
