# Generated by Django 5.1.15 on 2026-06-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_delivery_fee_alter_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sendo_shipment_id",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Sendo shipment id"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="sendo_status",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="statut livraison Sendo"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="sendo_tracking_token",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="jeton de suivi Sendo"
            ),
        ),
    ]
