# Generated by Django 5.1.15 on 2026-07-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_settlement"),
        ("orders", "0005_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="delivery.deliveryzone",
                verbose_name="zone de livraison",
            ),
        ),
    ]
